### ISSUE TITLE
Case preservation preference

### ISSUE THREAD

**Issue by AesaraB** [AesaraB/contextual-wiktionary#22]
> > > Thank you for making this awesome add-on!
> > > I would like to request a new preference to make the searches preserve case.
> > > At the moment, searches are converted to lower case.§ For example, if you select the word `Regal` then you are shown the Wiktionary entry for the word `regal`. This is adequate for English.
> > > Unfortunately, this does not work for German and other languages where capitalization changes the meaning of the word. In German, `Regal `with a capital `R` means "bookcase"; `regal` with a lower-case `r` is not a German word and there is no entry for German on the Wiktionary page.
> > > § I have zero experience with Javascript, but I believe this is the code that converts the selection to lower case:
> > > ```
> > > if (selectionText.toUpperCase() !== selectionText) {
> > > 		selectionText = selectionText.toLowerCase
> > > ```

> > I've been messing around with the code for this extension recently, it's quite a big problem to work with capitalisation in the English Wiktionary API, as definitions are case-sensitive, and by default lowercase; modifying case preservation by removing the selection normalisation feature would break more things than it would fix, so the solution would have to be more clever.
> > So, either:
> > 
> > - A list of proper nouns for each language with (a) alphabet(s) featuring capitalised letters would need to be implemented and referenced with the selection text, thereafter the extension would have choose circumstantially, whether to go to the definition for the proper noun or otherwise (i.e. for words with separate capitalised and uncapitalised definitions).
> > - Words with uppercase letters should forgo accessing a definition directly using the selection text, and instead use Wiktionary's search function to:
> >     1.  See if there exists a proper noun or acronym for the selection text
> >     2. If one exists, go to that definition; otherwise find the word definition without any capitalisation.
> >     3. If no definition can be found, then go to the corresponding page, where similar definitions could be referenced.
> > Both solutions would have this same issue with uncapitalised proper nouns, however.

> Wow, did not know such case sensitive differences existed.
> It does indeed seem like an important thing, however, I still want to keep the original behavior where words are lowercased first. I myself – and I expect many others – use this add-on mostly to check on meanings of English words.
> Perhaps a link to the original case-sensitive version next to the first header would suffice. Would require 2 clicks for the word, but I don't see a better way here.

[Copied from Gitlab](https://gitlab.com/losnappas/Context-menu-Wiktionary/-/issues/24).

**Comment by AesaraB** [comment]
To solve this I think there are three parts that need to be addressed:

1. Create a config for case preservation
2. Create an togglable option to enable case preservation
3. Read the config and pass the desired preference to the define() script.

**Comment by Alex-Kent** [comment]
An additional approach would be to first search for the capitalized form and if no definition is found to then fall back to searching for the lowercase form.  An example of where this would be useful is for **Sumer** where the capitalized form is far more common than the lowercase form.
