### ISSUE TITLE
Enhancement suggestion: allowing a default language other than English.

### ISSUE THREAD

**Issue by Valteur** [AesaraB/contextual-wiktionary#26]
I'm using your extension to learn a new language (Vietnamese). When I encounter a word I don't know, I check its definition in English on Wiktionary thanks to your extension.

For some words, I have to scroll very far down to access the definition in Vietnamese. Is it possible to make a setting that we can have a different default language than Enlgish ? (or maybe multiple favourite languages)

**Comment by Valteur** [comment]
Same as https://gitlab.com/losnappas/Context-menu-Wiktionary/-/issues/22

**Comment by Valteur** [comment]
For my usage, changing in the code all `.en` into `.vi`, and the `'en'` into `'vi'` works.

I think others might like it to be a setting.

**Comment by AesaraB** [comment]
Hi, thanks for writing; I'd be happy to look into this soon, can you provide some examples as to why the autoscroll feature currently integrated is inadequate?

**Comment by Valteur** [comment]
I didn't know about the autoscroll feature. (The only way to set this up is to click on a language. Correct ?) The autoscroll feature is good enough I guess.

**Comment by AesaraB** [comment]
Yes, click on a language and it will autoscroll. Changes occur when you close and reopen the popup. Click on an autoscrolled language header again and it will unset the scroll.
