### ISSUE TITLE
TypeError: this.getPlacementOfWidget(...) is null

### ISSUE THREAD

**Issue by marekoid** [AesaraB/contextual-wiktionary#29]
Hi, I added the plugin but upon selecting a word and clicking the "Define" button from the contextual menu, nothing happens. In the console I see the following entry being added:
```
TypeError: this.getPlacementOfWidget(...) is null[CustomizableUI.jsm:2043:21](resource:///modules/CustomizableUI.jsm)
    showWidgetView resource:///modules/CustomizableUI.jsm:2043
    handleWidgetCommand resource:///modules/CustomizableUI.jsm:2074
    handleWidgetCommand self-hosted:1285
    triggerAction chrome://browser/content/parent/ext-browserAction.js:363
    openPopup chrome://browser/content/parent/ext-browserAction.js:663
    openPopup self-hosted:1181
    result resource://gre/modules/ExtensionParent.jsm:935
    withPendingBrowser resource://gre/modules/ExtensionParent.jsm:491
    result resource://gre/modules/ExtensionParent.jsm:935
    callAndLog resource://gre/modules/ExtensionParent.jsm:897
    recvAPICall resource://gre/modules/ExtensionParent.jsm:934
    AsyncFunctionNext self-hosted:692
```
The browser I'm running is Firefox 91.9.0esr. Please help.

**Comment by AesaraB** [comment]
Hi, please put the Contextual Wiktionary popup button on your toolbar and try using the context menu 'define' again.

**Comment by marekoid** [comment]
Hi, thank you, it works now! Not sure if the issue shouldn't remain open as it's unclear that the plugin's button needs to be placed on the toolbar. I don't remember removing it after the installation so it looks like it's not added automatically. It would be nice if the plugin worked without that need or at least handle that error and display a message with that instruction.

**Comment by AesaraB** [comment]
This has happened before, and I'm fairly convinced it's a FIrefox bug; I plan to refactor the code in a couple of months because it's more or less just black magic to me at this point, which also means it's a bit difficult for me to raise an issue on Firefox's issue tracker.

**Comment by AesaraB** [comment]
I just tested this again, and it is no longer a problem.
