### ISSUE TITLE
Allow binding a keyboard shortcut to activate the extension with the currently selected text

### ISSUE THREAD

**Issue by Alice-Cheshire** [AesaraB/contextual-wiktionary#30]
Just like the title suggests, it'd be convenient if we could set a keybinding to activate the extension with a keyboard shortcut instead of always having to use the context menu. Or just having a default one that's not too difficult to hit quickly would be an option as well if you don't want to make things too complicated.

**Comment by AesaraB** [comment]
Hi, do you have any examples of other add-ons that do this? I'd prefer not to allow such a feature as a shortcut may break parts of websites -- or Firefox, so if this is implemented it will be disabled by default.

**Comment by Alice-Cheshire** [comment]
Not off the top of my head. If any I use do have shortcuts like that, I'm actually not aware of them, with the exception of [Yomichan](https://addons.mozilla.org/en-US/firefox/addon/yomichan/) which allows you to set it so that shift/ctrl/alt/win can make its definitions pop up. And having it disabled by default is no problem for me.

**Comment by AesaraB** [comment]
This feature is added. There isn't a shortcut by default.

Keep your eyes peeled for an update. When v1.4 rolls out you can assign a shortcut [using this guide](https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox)
