### ISSUE TITLE
Add option to choose which languages are displayed by default

### ISSUE THREAD

**Issue by Alex-Kent** [AesaraB/contextual-wiktionary#35]
It would be nice to have the option to choose one or more languages to display by default.  Currently one has to click "Other languages" to see them.  Given that when I'm doing a search it's usually for a word in a foreign language having the extra click is rather annoying.

**Comment by AesaraB** [comment]
Hi, if you click on the language heading (e.g. German), there's an option to autoscroll to a language. Please let me know if this addresses your concern.
