### ISSUE TITLE
Words' gender should be shown (when applicable)

### ISSUE THREAD

**Issue by Alex-Kent** [AesaraB/contextual-wiktionary#36]
In many languages (e.g. German, French) nouns are gendered and it's important to know which one applies to a given word.  This should be shown in the definition.  On the wiktionary website this is indicated by the *f* (feminine), *m* (masculine), and *n* (neuter) abbreviations being shown after the word.

**Comment by AesaraB** [comment]
Can you please link a couple Wiktionary pages for words in gendered languages?

**Comment by AesaraB** [comment]
Hi, I've looked into the API and this is currently not technically possible. I'll add it if the API improves.
