### ISSUE TITLE
Compatibility with other search related extension

### ISSUE THREAD

**Issue by JLuc** [AesaraB/contextual-wiktionary#37]
contextual-wiktionary did work fine but until i installed some other search related extension and tried them. Since then, the option appear in the contextual menu, but it does nothing at all : no popup window appears and no error in the console.
AFAIK I switched all the other recently installed extension OFF, but contextual-wiktionary still doesnt work.

Is there a known way i can fix this issue ?
How can i better diagnose the issue so as to provide usefull debug data ?

With Firefox 108.0.2 (64 bits) on Ubuntu 22.10

**Comment by AesaraB** [comment]
Hi, is the extension button visible in the menubar?
![image](https://user-images.githubusercontent.com/64518882/211193841-7dbb4b2d-ec5c-4871-94f3-70bf1b1b2ab0.png)

**Comment by JLuc** [comment]
No, since i asked FF to not display it. 
I went to Customize toolbar so as to display the button and now the popup "define" window appears OK.
I suppose it's not possible to both have this sort of popup display and no button.
Thanks a lot for your answer.
